Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  copyright: And in case I don't see you - good afternoon, good evening and goodnight!
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  #approot: "http://www.example.com"
  <<: *defaults
